[package]
name = "jonathan_userdb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"]}
serde_json = "1.0.71"
# rocket = { git = "https://github.com/SergioBenitez/Rocket", tag = "v0.5.0-rc.1" }
rocket = "0.5.0-rc.1"